
language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - "sudo apt-get update -qq"
  - "sudo apt-get install -qq mecab mecab-ipadic-utf8 libmecab-dev"
install:
  - "python setup.py install"
  - "pip install coveralls"
script:
  - "nosetests --with-coverage --cover-package=mlask"
after_success:
  - coveralls
